CREATE TABLE [SRSDW].[ProductValidation](
	[SRSITEM] [varchar](30) NOT NULL,
	[GVPItemKey] [varchar](60) NULL,
	[GVPItemNumber] [nvarchar](60) NULL,
	[SRSCAT6] [varchar](20) NOT NULL,
	[MatchItemKey] [varchar](20) NULL,
	[SRSDESC] [varchar](60) NOT NULL,
	[GVPName] [nvarchar](100) NULL,
	[MatchDesc] [varchar](10) NULL,
	[SRSUNITS] [numeric](6, 0) NOT NULL,
	[GVPUnits] [decimal](18, 1) NULL,
	[MatchUnits] [varchar](10) NULL,
	[SELLUNIT] [numeric](6, 0) NOT NULL,
	[SRSALCPCT] [numeric](4, 1) NOT NULL,
	[GVPAlcoholByVolume] [decimal](10, 6) NULL,
	[MatchAlcPct] [varchar](10) NULL,
	[SRSBRAND] [varchar](20) NOT NULL,
	[GVPBrandKey] [varchar](10) NULL,
	[BRDESC] [varchar](35) NOT NULL,
	[GVPBrandName] [nvarchar](100) NULL,
	[MatchBrandName] [varchar](10) NULL,
	[SRSLabelKey] [varchar](20) NOT NULL,
	[GVPLabelKey] [varchar](70) NULL,
	[SRSLabelName] [varchar](80) NOT NULL,
	[GVPLabelName] [nvarchar](200) NULL,
	[MatchLabelName] [varchar](10) NULL,
	[SRSPKGTYP] [varchar](10) NOT NULL,
	[GVPPackageType] [nvarchar](20) NULL,
	[MatchPackageType] [varchar](10) NULL,
	[PKGSIZ] [varchar](10) NOT NULL,
	[LASTCHNG] [varchar](8) NOT NULL,
	[SRSSTATUS] [varchar](1) NOT NULL,
	[GVPStatus] [varchar](10) NULL,
	[MatchStatus] [varchar](10) NULL,
	[SRSIEOZPC] [numeric](8, 3) NOT NULL,
	[SRSIEMLPC] [numeric](9, 3) NOT NULL,
	[OUNCE] [numeric](6, 0) NOT NULL,
	[IEUVOLD] [varchar](15) NULL,
	[SRSLiterFromOz] [numeric](10, 9) NOT NULL,
	[SRSLiterFromML] [numeric](4, 2) NOT NULL,
	[GVPLiterVolume] [decimal](21, 12) NULL,
	[MatchLiterVolume] [decimal](21, 12) NULL,
	[MatchOZVolume] [numeric](4, 3) NULL,
	[IEUSIZE] [numeric](9, 3) NOT NULL,
	[IEUPACK] [varchar](4) NOT NULL,
	[IEUUOM] [varchar](5) NOT NULL,
	[IEPKGT] [varchar](10) NOT NULL,
	[GVPSizeKey] [decimal](21, 12) NULL,
	[SRSIEVINTAGE] [numeric](4, 1) NOT NULL,
	[GVPVintage] [varchar](40) NULL,
	[MatchVintage] [varchar](10) NULL,
	[IESEASONAL] [varchar](1) NOT NULL,
	[IEMILITARY] [varchar](1) NOT NULL,
	[ITCTYPE] [varchar](1) NULL,
	[GVPContainerType] [varchar](1) NULL,
	[SRSRADVolume] [int] NULL,
	[SRSRADVolumeLast120Days] [int] NULL,
	[CTLSum] [int] NULL,
	[Data Validation RAD Volume] [int] NULL,
	[CTLSSum] [int] NULL,
	[SRSDeplDAVolume] [int] NULL,
	[Data Validation Activity#] [int] NULL,
	[Data Validation Goals] [int] NULL,
	[TERRPTR] [varchar](20) NOT NULL,
	[FILENAME] [varchar](100) NOT NULL,
	[CASEGTIN] [numeric](16, 0) NOT NULL,
	[RETGTIN] [numeric](16, 0) NOT NULL,
	[ACTDATE] [numeric](10, 0) NOT NULL,
	[DEADATE] [numeric](10, 0) NOT NULL,
	[WEIGHT] [numeric](6, 2) NOT NULL,
	[PCASPAL] [numeric](5, 0) NOT NULL,
	[SCASPAL] [numeric](5, 0) NOT NULL,
	[PKGCD] [varchar](20) NOT NULL,
	[GEO] [varchar](10) NOT NULL,
	[CUBE] [numeric](4, 2) NOT NULL,
	[CAT1] [varchar](20) NOT NULL,
	[CAT2] [varchar](20) NOT NULL,
	[CAT3] [varchar](20) NOT NULL,
	[CAT4] [varchar](20) NOT NULL,
	[CAT5] [varchar](20) NOT NULL,
	[IEDATECD] [varchar](1) NOT NULL,
	[IESUPPDESC] [varchar](80) NOT NULL,
	[IEGTN3] [numeric](14, 1) NOT NULL,
	[IECDDAYS] [numeric](3, 1) NOT NULL,
	[IECSWIDTH] [numeric](5, 2) NOT NULL,
	[IECSHEIGHT] [numeric](5, 2) NOT NULL,
	[IECSLENGTH] [numeric](5, 2) NOT NULL,
	[IEPKWIDTH] [numeric](5, 2) NOT NULL,
	[IEPKHEIGHT] [numeric](5, 2) NOT NULL,
	[IEPKLENGTH] [numeric](5, 2) NOT NULL,
	[IECSPTIER] [numeric](3, 1) NOT NULL,
	[IECATID8] [varchar](20) NOT NULL,
	[IECATLABEL8] [varchar](80) NOT NULL,
	[IECATID9] [varchar](20) NOT NULL,
	[IECATLABEL9] [varchar](80) NOT NULL,
	[IECATID10] [varchar](20) NOT NULL,
	[IECATLABEL10] [varchar](80) NOT NULL,
	[IECATID11] [varchar](20) NOT NULL,
	[IECATLABEL11] [varchar](80) NOT NULL,
	[IECATID12] [varchar](20) NOT NULL,
	[IECATLABEL12] [varchar](80) NOT NULL
) ON [PRIMARY]
GO